library(here)
print("==============================")
print(Sys.time())
source(here::here("correlaid-analytics/01_get_daily_analytics.R"))
rmarkdown::render(here::here("README.Rmd"))
source(here::here("correlaid-analytics/02_git.R"))
